In [ ]:
# Task 1
class Student:
  count = 0
  def __init__(self,name,dept,age,cg):
    self.name = name
    self.dept = dept
    self.age = age
    self.cg = cg
    Student.count+=1

  def showDetails(self):

    print("ID:",Student.count)
    print("Name:",self.name)
    print("Department:",self.dept)
    print("Age:",self.age)
    print("CGPA:",self.cg)

  @classmethod
  def from_String(cls,x):
    info=x.split("-")
    information= cls(info[0],info[1],int(info[2]),float(info[3]))
    return information

s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()

ID: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
ID: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
ID: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
ID: 4
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96

In [ ]:
#Task 2
class Assassin:
  num_assassin = 0
  def __init__(self,name,rate):
    self.name = name
    self.rate = rate
    Assassin.num_assassin+=1
  def printDetails(self):
    print("Name:",self.name)
    print(f"Success rate:{self.rate}%")
    print("Total number of Assassin:",Assassin.num_assassin)
  @classmethod
  def failureRate(cls,name,rate):
    fRate = 100-rate
    obj1 = cls(name,fRate)
    return obj1
  @classmethod
  def failurePercentage(cls,name,rate):
    frate = 100-int(rate[:2])
    obj2 = cls(name,frate)
    return obj2

john_wick = Assassin('John Wick', 100)
john_wick.printDetails()
print('================================')
nagisa = Assassin.failureRate("Nagisa", 20)
nagisa.printDetails()
print('================================')
akabane = Assassin.failurePercentage("Akabane", "10%")
akabane.printDetails()

Name: John Wick
Success rate:100%
Total number of Assassin: 1
================================
Name: Nagisa
Success rate:80%
Total number of Assassin: 2
================================
Name: Akabane
Success rate:90%
Total number of Assassin: 3

In [ ]:
# Task 3
class Passenger:
  count = 0
  def __init__(self,name):
    self.name = name
    Passenger.count += 1

  def set_bag_weight(self,wgt):

    self.Bus_fare = 450
    self.wgt = wgt
    if self.wgt>=21 and self.wgt<=50:
      self.Bus_fare+=50
    elif self.wgt>50:
      self.Bus_fare+=100
  def printDetail(self):
    print("Name:",self.name)
    print("Bus Fare:",self.Bus_fare)
print('Total Passenger:', Passenger.count)
p1 = Passenger('Jack')
p1.set_bag_weight(90)
p2 = Passenger('Carol')
p2.set_bag_weight(10)
p3 = Passenger('Mike')
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print('Total Passenger:', Passenger.count)

Total Passenger: 0
=========================
Name: Jack
Bus Fare: 550
=========================
Name: Carol
Bus Fare: 450
=========================
Name: Mike
Bus Fare: 500
=========================
Total Passenger: 3

In [ ]:
# Task 4
class Travel:
  count = 0
  def __init__(self,start,end):
    self.start = start
    self.end = end
    self.time = 1
    Travel.count += 1

  def display_travel_info(self):
   return f"Source:{self.start} \nDestination:{self.end}\nFlight Time:{self.time}:00"

  def set_time(self,time):
    self.time = time

  def set_destination(self,end):
    self.end = end

  def set_source(self,start):
    self.start = start


print("No. of Traveller =", Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print("No. of Traveller =",Travel.count)

No. of Traveller = 0
=======================
Source:Dhaka
Destination:India
Flight Time:1:00
=======================
Source:Kuala Lampur
Destination:Dhaka
Flight Time:23:00
=======================
Source:Dhaka
Destination:Germany
Flight Time:15:00
=======================
Source:Malaysia
Destination:Canada
Flight Time:9:00
=======================
No. of Traveller = 4

In [ ]:
# Task 5
class Employee:
  def __init__(self,name,workingperiod):
    self.name=  name
    self.workingPeriod = workingperiod

  @classmethod
  def employeeByJoiningYear(cls,name,year):
    workingPeriod = 2023-year
    f2 = cls(name,workingPeriod)
    return f2

  @staticmethod
  def experienceCheck(workingperiod,gender):
    if workingperiod<3 and gender=="male":
      return ("He is not experienced")
    elif workingperiod<3 and gender=="female":
      return ("She is not experienced")
    elif workingperiod>3 and gender=="male":
      return ("He is experienced")
    else:
      return ("She is experienced")


employee1 = Employee('Dororo', 3)
employee2 = Employee.employeeByJoiningYear('Harry', 2016)
print(employee1.workingPeriod)
print(employee2.workingPeriod)
print(employee1.name)
print(employee2.name)
print(Employee.experienceCheck(2, "male"))
print(Employee.experienceCheck(3, "female"))

3
7
Dororo
Harry
He is not experienced
She is experienced

In [ ]:
# TAsk 6
class Laptop:
  laptopCount = 0
  def __init__(self,name,count):
    self.name= name
    self.count = count
    Laptop.laptopCount +=self.count
  @classmethod
  def advantage(cls):
    print("Laptops are portable")
  @classmethod
  def resetCount(cls):
    cls.laptopCount = 0

lenovo = Laptop("Lenovo", 5)
dell = Laptop("Dell", 7)
print(lenovo.name, lenovo.count)
print(dell.name, dell.count)
print("Total number of Laptops", Laptop.laptopCount)
Laptop.advantage()
Laptop.resetCount()
print("Total number of Laptops", Laptop.laptopCount)

Lenovo 5
Dell 7
Total number of Laptops 12
Laptops are portable
Total number of Laptops 0

In [ ]:
class Cat:
  Number_of_cats = 0
  def __init__(self,color,active):
    self.color = color
    self.active = active
    Cat.Number_of_cats+=1
  def printCat(self):
    print(f"{self.color} cat is {self.active}")
  def changeColor(self,color):
    self.color = color
  @classmethod
  def no_parameter(cls):
    color = "White"
    active = "Sitting"
    return cls(color,active)
  @classmethod
  def first_parameter(cls,color):
    active = "Sitting"
    c = cls(color,active)
    return c
  @classmethod
  def second_parameter(cls,active):
    color = "Grey"
    return cls(color,active)

print("Total number of cats:", Cat.Number_of_cats)
c1 = Cat.no_parameter()
c2 = Cat.first_parameter("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c5 = Cat.second_parameter("playing")
print("=======================")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c5.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()
print("=======================")
print("Total number of cats:", Cat.Number_of_cats)

Total number of cats: 0
=======================
White cat is Sitting
Black cat is Sitting
Brown cat is jumping
Red cat is purring
Grey cat is playing
Blue cat is Sitting
Purple cat is jumping
=======================
Total number of cats: 5

In [ ]:
# Task 8
import math
class Cylinder:
  radius = 5
  height = 18
  def __init__(self,rad,hgt):
    print(f"Default radius={Cylinder.radius} and height={Cylinder.height}")
    Cylinder.radius = rad
    Cylinder.height = hgt
    print(f"Updated radius={Cylinder.radius} and height={Cylinder.height}")

  @staticmethod
  def area(r,h):
    area = 2*math.pi*r*h + 2*math.pi*r**2
    print("Area:",area)

  @staticmethod
  def volume(r,h):
    vol = math.pi*r**2*h
    print("Volume:",vol)

  @classmethod
  def swap(cls,h,r):
    return cls(r,h)

  @classmethod
  def changeFormat(cls,info):
    info = info.split("-")
    rad = float(info[0])
    h = float(info[1])
    return cls(rad,h)

c1 = Cylinder(0,0)
Cylinder.area(c1.radius,c1.height)
Cylinder.volume(c1.radius,c1.height)
print("===============================")
c2 = Cylinder.swap(8,3)
c2.area(c2.radius,c2.height)
c2.volume(c2.radius,c2.height)
print("===============================")
c3 = Cylinder.changeFormat("7-13")
c3.area(c3.radius,c3.height)
c3.volume(c3.radius,c3.height)
print("===============================")
Cylinder(0.3,5.56).area(Cylinder.radius,Cylinder.height)
print("===============================")
Cylinder(3,5).volume(Cylinder.radius,Cylinder.height)

Default radius=5 and height=18
Updated radius=0 and height=0
Area: 0.0
Volume: 0.0
===============================
Default radius=0 and height=0
Updated radius=3 and height=8
Area: 207.34511513692635
Volume: 226.1946710584651
===============================
Default radius=3 and height=8
Updated radius=7.0 and height=13.0
Area: 879.645943005142
Volume: 2001.1945203366981
===============================
Default radius=7.0 and height=13.0
Updated radius=0.3 and height=5.56
Area: 11.045839770021713
===============================
Default radius=0.3 and height=5.56
Updated radius=3 and height=5
Volume: 141.3716694115407

In [ ]:
# Task 9
class Student:
  total_stud =  0
  bracu_stud = 0
  other_inst_stud = 0
  def __init__(self,name,dept,inst="BRAC University"):
    self.name = name
    self.dept = dept
    self.inst = inst
    Student.total_stud += 1
    if self.inst == "BRAC University":
      Student.bracu_stud +=1
    else:
      Student.other_inst_stud +=1
  def individualDetail(self):
    print("Name:",self.name)
    print("Department:",self.dept)
    print("Institution:",self.inst)
  @classmethod
  def printDetails(cls):
    print("Total Student(s):",cls.total_stud)
    print("BRAC University Student(s):",cls.bracu_stud)
    print("Other Institution Student(s):",cls.other_inst_stud)
  @classmethod
  def createStudent(cls,name,dept,inst="BRAC University"):
    return cls(name,dept,inst)

Student.printDetails()
print('#########################')
mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()
print('========================')
harry = Student.createStudent('Harry Potter', "Defence Against Dark Arts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()
print('=========================')
levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

Total Student(s): 0
BRAC University Student(s): 0
Other Institution Student(s): 0
#########################
Name: Mikasa Ackerman
Department: CSE
Institution: BRAC University
------------------------------------------
Total Student(s): 1
BRAC University Student(s): 1
Other Institution Student(s): 0
========================
Name: Harry Potter
Department: Defence Against Dark Arts
Institution: Hogwarts School
-------------------------------------------
Total Student(s): 2
BRAC University Student(s): 1
Other Institution Student(s): 1
=========================
Name: Levi Ackerman
Department: CSE
Institution: BRAC University
--------------------------------------------
Total Student(s): 3
BRAC University Student(s): 2
Other Institution Student(s): 1

In [ ]:
# TAsk 10
class SultansDine:
  num_branch = 0
  total_sell = 0
  lst = []
  def __init__(self,loc):
    self.loc = loc
    SultansDine.num_branch+=1
  def sellQuantity(self,sell):
    if sell<10:
      self.branch_sell = sell*300
    elif sell<20:
      self.branch_sell = sell*350
    else:
      self.branch_sell = sell*400
    SultansDine.total_sell+=self.branch_sell

  def branchInformation(self):
     print("Branch Name:",self.loc)
     print("Branch Sell:",self.branch_sell,"Taka")
     SultansDine.lst.append(self.loc)
     SultansDine.lst.append(self.branch_sell)

  @classmethod
  def details(cls):
    print("Total Number of branch(s):",cls.num_branch)
    print("Total Sell:",cls.total_sell,"Taka")
    for i in range(0,len(cls.lst),2):
      print(f"Branch name: {cls.lst[i]},Branch sell: {cls.lst[i+1]}")
      print(f"Branch consists of total sell's: {round((cls.lst[i+1]/cls.total_sell)*100,2)}%")

SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s): 0
Total Sell: 0 Taka
########################
Branch Name: Dhanmondi
Branch Sell: 10000 Taka
-----------------------------------------
Total Number of branch(s): 1
Total Sell: 10000 Taka
Branch name: Dhanmondi,Branch sell: 10000
Branch consists of total sell's: 100.0%
========================
Branch Name: Baily Road
Branch Sell: 5250 Taka
-----------------------------------------
Total Number of branch(s): 2
Total Sell: 15250 Taka
Branch name: Dhanmondi,Branch sell: 10000
Branch consists of total sell's: 65.57%
Branch name: Baily Road,Branch sell: 5250
Branch consists of total sell's: 34.43%
========================
Branch Name: Gulshan
Branch Sell: 2700 Taka
-----------------------------------------
Total Number of branch(s): 3
Total Sell: 17950 Taka
Branch name: Dhanmondi,Branch sell: 10000
Branch consists of total sell's: 55.71%
Branch name: Baily Road,Branch sell: 5250
Branch consists of total sell's: 29.25%
Branch name: Gulshan,Branch sell: 2700
Branch consists of total sell's: 15.04%